/ ‘asymptote_preview’

diff --git a/asymptote_preview b/asymptote_preview
--- a/asymptote_preview
+++ b/asymptote_preview
@@ -12,6 +12,10 @@ extension="${filename##*.}"
 filename="${filename%.*}"
 outfile="$directory/$filename.eps"
 first_run=true
+if [ ! -f $filepath ]; then
+  echo "Input file not found"
+  exit 1;
+fi
 
 echo "Starting..."
 while true; do
