/ ‘Class_Notes/2020/Fall/Algebraic Curves/AlgebraicCurves.pdf’ / ‘Class_Notes/2020/Fall/Algebraic Curves/Makefile’ + ‘Class_Notes/2020/Fall/Algebraic Curves/tex_tempfiles/AlgebraicCurves.lof’

diff --git a/Class_Notes/2020/Fall/Algebraic Curves/Makefile b/Class_Notes/2020/Fall/Algebraic Curves/Makefile
--- a/Class_Notes/2020/Fall/Algebraic Curves/Makefile
+++ b/Class_Notes/2020/Fall/Algebraic Curves/Makefile
@@ -1,5 +1,6 @@
 SHELL:=/bin/zsh
 FILENAME="AlgebraicCurves"
+TEMP_DIR="/tmp/"
 
 all: pdf html clean_bib
 	type clr_green 2>&1 >/dev/null || { echo "Sourcing"; source "$$DOTFILES_ROOT/.bash_colors";}
@@ -9,11 +10,11 @@ all: pdf html clean_bib
 
 ## Markdown Output
 markdown:
-	ruby -ryaml -e "p YAML.load(STDIN.read)" < data.yaml || { echo "Error parsing data.yaml" && exit 1; };
-	cp -r $$PANDOC_DIR .;
-	cat "./.pandoc/custom/latexmacs.tex" > $(FILENAME).md;
-	awk 'FNR==1{print ""}1' ./sections/*.md  >> $(FILENAME).md;
-	awk 'FNR==1{print ""}1' ./sections/*.md  | pandoc_stripmacros.sh > $(FILENAME)_stripped.md;
+	@ruby -ryaml -e "p YAML.load(STDIN.read)" < data.yaml || { echo "Error parsing data.yaml" && exit 1; };
+	@cp -r $$PANDOC_DIR .;
+	@cat "./.pandoc/custom/latexmacs.tex" > $(FILENAME).md;
+	@awk 'FNR==1{print ""}1' ./sections/*.md  >> $(FILENAME).md;
+	@awk 'FNR==1{print ""}1' ./sections/*.md  | pandoc_stripmacros.sh > $(FILENAME)_stripped.md;
 	echo "Markdown done."
 
 ## LaTeX Output
@@ -23,7 +24,7 @@ latex: markdown
 
 ## PDF Output
 pdf: markdown test latex
-	mkdir -p tex_tempfiles;
+	@mkdir -p tex_tempfiles;
 	latexmk --shell-escape -pdf $(FILENAME).tex -quiet -outdir=tex_tempfiles && cp tex_tempfiles/$(FILENAME).pdf .;
 	echo "PDF done";
 
@@ -47,23 +48,24 @@ test: markdown latex
 
 clean_bib: 
 	biber --tool --output_align --output_indent=2 --output_fieldcase=lower $(FILENAME).bib;
-	mv $(FILENAME)_bibertool.bib $(FILENAME).bib || true;
-	rm $(FILENAME).bib.blg || true;
+	@mv $(FILENAME)_bibertool.bib $(FILENAME).bib || true;
+	@rm $(FILENAME).bib.blg || true;
 
 .SILENT:
 
 clean:
-	rm tex_tempfiles -rf || true;
-	rm -rf latex.out || true;
+	@rm tex_tempfiles -rf || true;
+	@rm -rf latex.out || true;
 
 reset:
-	rm ./.pandoc -rf || true;
-	rm $(FILENAME).md -f || true;
-	rm $(FILENAME)_stripped.md -f || true;
-	rm $(FILENAME).tex -f || true;
-	rm $(FILENAME).html -f || true;
-	rm $(FILENAME).pdf -f || true;
-	rm build.log sections/build.log || true;
+	@yes | rm /tmp/* || true;
+	@rm ./.pandoc -rf || true;
+	@rm $(FILENAME).md -f || true;
+	@rm $(FILENAME)_stripped.md -f || true;
+	@rm $(FILENAME).tex -f || true;
+	@rm $(FILENAME).html -f || true;
+	@rm $(FILENAME).pdf -f || true;
+	@rm build.log sections/build.log || true;
 
 .PHONY: clean
 
